server:
  port: 9091

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE/
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE/
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE/
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
        - id: PAYPAL-SERVICE
          uri: lb://PAYPAL-SERVICE/
          predicates:
            - Path=/paypal/**
          filters:
            - AuthenticationFilter
        - id: CREDITCARD-SERVICE
          uri: lb://CREDITCARD-SERVICE/
          predicates:
            - Path=/credit-card/**
          filters:
            - AuthenticationFilter
        - id: SHIPPING-SERVICE
          uri: lb://SHIPPING-SERVICE/
          predicates:
            - Path=/shipment/**
          filters:
            - AuthenticationFilter
        - id: STOCK-SERVICE
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/stock/**
          filters:
            - AuthenticationFilter
        - id: BANKACCOUNT-SERVICE
          uri: lb://BANKACCOUNT-SERVICE/
          predicates:
            - Path=/bank-transfer/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka


jwt:
  secret: testing
  validity: 20
  authDisabled: true

